language: python
sudo: false
python: 3.6
env:
 - LINT=
 - LINT=1
install:
 - pip install .
 - pip install html-json-forms
 - npm install node-qunit-phantomjs
 - npm install jshint
before_script:
 - python -m tests.server &
 - cd tests
 - wq collectjson
 - wq init
 - wq scss --indir scss --outdir css
 - cd ..
script:
 - ./runtests.sh
